"""Lyricist Agent (M6) — RAG-grounded devotional lyric writing (FR-3..FR-5).

In mock/offline mode the agent composes structured lyrics deterministically from
the request, retrieved KB context, and the Learning File's pronunciation fixes.
When a real LLM is configured it drafts via the model, then self-validates terms.
"""

from __future__ import annotations

from typing import Any, Optional

from ..logging_utils import get_logger
from ..models import LyricLine, LyricsDoc, LyricSection, ProductionRequest

logger = get_logger("agent.lyricist")


def _retrieve_context(request: ProductionRequest, k: int = 6) -> tuple[list[dict], float]:
    """Best-effort RAG retrieval; returns (hits, confidence). Never fatal."""
    try:
        from ..rag.retriever import retrieve

        query = f"{request.deity} {request.theme} {request.mood.value}"
        hits = retrieve(query, k=k)
        confidence = min(1.0, 0.5 + 0.1 * len(hits)) if hits else 0.4
        return hits, confidence
    except Exception as exc:  # noqa: BLE001 - RAG optional / store may be empty
        logger.debug("RAG retrieval unavailable: %s", exc)
        return [], 0.4


def _pron_hint(term: str, learning: dict) -> Optional[str]:
    fixes = (learning or {}).get("pronunciation_fixes", {}) or {}
    for key, hint in fixes.items():
        if term.lower() in key.lower() or key.lower() in term.lower():
            return hint
    return None


def _line(text: str, learning: dict, term: Optional[str] = None) -> LyricLine:
    hint = _pron_hint(term or text, learning) if term else None
    return LyricLine(text=text, pronunciation_hint=hint)


def _parse_override(text: str, language: str) -> LyricsDoc:
    """Normalize a user-supplied lyrics override into a LyricsDoc."""
    blocks = [b.strip() for b in text.split("\n\n") if b.strip()]
    sections: list[LyricSection] = []
    for i, block in enumerate(blocks):
        name = "mukhda" if i == 0 else "antara"
        lines = [LyricLine(text=ln) for ln in block.splitlines() if ln.strip()]
        if lines:
            sections.append(LyricSection(name=name, lines=lines))  # type: ignore[arg-type]
    if not sections:
        sections = [LyricSection(name="mukhda", lines=[LyricLine(text=text.strip())])]
    return LyricsDoc(title_working="Custom Lyrics", language=language, sections=sections, rag_confidence=1.0)


def write_lyrics(
    request: ProductionRequest,
    learning: dict,
    antara_count: int = 2,
) -> LyricsDoc:
    """Produce a structured LyricsDoc (mukhda + antara×N + aarti outro).

    When a live LLM is configured (not mock mode), the lyrics are generated by
    the model and grounded in retrieved RAG context. On ANY failure — network
    error, invalid/empty JSON, validation error — we fall back to the
    deterministic template. Mock mode always uses the template.
    """
    if request.lyrics_override:
        logger.info("Using provided lyrics_override")
        return _parse_override(request.lyrics_override, request.language)

    from ..config import get_settings

    if not get_settings().is_mock():
        doc = _llm_lyrics(request, learning, antara_count)
        if doc is not None:
            return doc
        logger.warning("LLM lyric generation failed; falling back to template")

    return _template_lyrics(request, learning, antara_count)


def _build_system_prompt(request: ProductionRequest, learning: dict) -> str:
    """System prompt skeleton from docs/AGENTS.md §Lyricist."""
    artist = (learning or {}).get("artist_name") or "the artist"
    return (
        f"You are a devotional lyricist for {artist}. Write {request.language} "
        f"bhajan lyrics for {request.deity} on the theme \"{request.theme}\", "
        f"mood \"{request.mood.value}\". Use ONLY the retrieved context for any "
        "scriptural/biographical claims; never invent scripture. Mirror the "
        "artist's vocabulary and phrasing shown in any retrieved past lyrics. "
        "Output sections: a mukhda (refrain), two antara verses, and an optional "
        "aarti outro. For every line include a pronunciation hint for sacred "
        "terms (or null when none apply). Keep dignity and tradition at all times."
    )


def _build_user_prompt(
    request: ProductionRequest,
    learning: dict,
    hits: list[dict],
    antara_count: int,
) -> str:
    """User prompt: RAG context + pronunciation fixes + strict JSON schema."""
    parts: list[str] = []

    if hits:
        ctx_lines: list[str] = []
        for h in hits:
            text = ""
            if isinstance(h, dict):
                text = h.get("text") or h.get("content") or h.get("payload") or ""
            text = str(text).strip()
            if text:
                ctx_lines.append(f"- {text}")
        if ctx_lines:
            parts.append("Retrieved context (use for facts/style only):\n" + "\n".join(ctx_lines))

    fixes = (learning or {}).get("pronunciation_fixes", {}) or {}
    if fixes:
        fix_lines = [f"- {term}: {hint}" for term, hint in fixes.items()]
        parts.append("Known pronunciation fixes (apply as hints):\n" + "\n".join(fix_lines))

    parts.append(
        f"Write {max(1, antara_count)} antara verses. Return STRICT JSON only, "
        "matching exactly this shape (no markdown, no commentary):\n"
        "{\n"
        '  "title_working": str,\n'
        '  "sections": [\n'
        '    {"name": "mukhda|antara|aarti_outro",\n'
        '     "lines": [{"text": str, "pronunciation_hint": str|null}]}\n'
        "  ],\n"
        '  "devotional_terms": [str]\n'
        "}"
    )
    return "\n\n".join(parts)


def _llm_lyrics(
    request: ProductionRequest,
    learning: dict,
    antara_count: int,
) -> Optional[LyricsDoc]:
    """Generate lyrics with the configured LLM. Returns None on any failure."""
    try:
        from ..llm import get_llm

        hits, confidence = _retrieve_context(request)
        system = _build_system_prompt(request, learning)
        user = _build_user_prompt(request, learning, hits, antara_count)

        data = get_llm().complete_json(user, system=system)
        if not isinstance(data, dict) or not data:
            logger.debug("LLM returned empty/invalid JSON for lyrics")
            return None

        raw_sections = data.get("sections")
        if not isinstance(raw_sections, list) or not raw_sections:
            logger.debug("LLM JSON missing 'sections'")
            return None

        sections: list[LyricSection] = []
        for sec in raw_sections:
            if not isinstance(sec, dict):
                continue
            name = sec.get("name")
            if name not in ("mukhda", "antara", "aarti_outro"):
                continue
            raw_lines = sec.get("lines")
            if not isinstance(raw_lines, list):
                continue
            lines: list[LyricLine] = []
            for ln in raw_lines:
                if isinstance(ln, dict):
                    text = ln.get("text")
                    if text:
                        hint = ln.get("pronunciation_hint")
                        lines.append(LyricLine(text=str(text), pronunciation_hint=hint))
                elif isinstance(ln, str) and ln.strip():
                    lines.append(LyricLine(text=ln.strip()))
            if lines:
                sections.append(LyricSection(name=name, lines=lines))  # type: ignore[arg-type]

        if not sections:
            logger.debug("LLM JSON produced no usable sections")
            return None

        terms = data.get("devotional_terms")
        if not isinstance(terms, list):
            terms = []
        terms = [str(t) for t in terms if t]

        title = data.get("title_working")
        title = str(title) if title else f"{request.theme.strip().title()} — {request.deity} Bhajan"

        return LyricsDoc(
            title_working=title,
            language=request.language,
            sections=sections,
            devotional_terms=terms,
            rag_confidence=confidence,
        )
    except Exception as exc:  # noqa: BLE001 - any failure → template fallback
        logger.warning("LLM lyric generation error: %s", exc)
        return None


def _template_lyrics(
    request: ProductionRequest,
    learning: dict,
    antara_count: int = 2,
) -> LyricsDoc:
    """Deterministic template lyrics (offline / fallback path)."""
    deity = request.deity or "Khatu Shyam"
    theme = request.theme.strip().title()
    hits, confidence = _retrieve_context(request)

    # Devotional terms we want pronounced correctly (seed from deity + learning).
    terms = [deity, "Shyam", "Khatu", "Darshan", "Aarti"]

    mukhda = LyricSection(
        name="mukhda",
        lines=[
            _line(f"Bolo {deity} ki jai, {deity} ki jai", learning, deity),
            _line(f"{theme} mein tere darshan paaye", learning, "Darshan"),
        ],
    )

    antaras: list[LyricSection] = []
    motifs = [
        ("Khatu naresh tere dware aaye", "Khatu"),
        ("Sheesh ke daani, bhakton ke palanhaar", "Shyam"),
        ("Teri mahima gaaye saara sansaar", deity),
        ("Morning ki bela mein bajti aarti", "Aarti"),
    ]
    for i in range(max(1, antara_count)):
        text, term = motifs[i % len(motifs)]
        antaras.append(
            LyricSection(
                name="antara",
                lines=[_line(text, learning, term), _line(f"{deity} sang man lag jaaye", learning, deity)],
            )
        )

    aarti_outro = LyricSection(
        name="aarti_outro",
        lines=[_line(f"Om Jai {deity} hare", learning, deity), _line("Bhakti bhaav se sab gaaye", learning)],
    )

    sections = [mukhda, *antaras, aarti_outro]
    doc = LyricsDoc(
        title_working=f"{theme} — {deity} Bhajan",
        language=request.language,
        sections=sections,
        devotional_terms=terms,
        rag_confidence=confidence,
    )
    return doc


def lyricist_node(state: dict) -> dict:
    """LangGraph node: write lyrics and persist them to the run dir."""
    from .. import runs

    request: ProductionRequest = state["request"]
    learning: dict = state.get("learning", {})
    doc = write_lyrics(request, learning)

    run_id = state["run_id"]
    path = runs.run_dir(run_id) / "lyrics.json"
    path.write_text(doc.model_dump_json(indent=2), encoding="utf-8")

    artifacts = dict(state.get("artifacts", {}))
    artifacts["lyrics"] = str(path)
    if doc.rag_confidence < 0.5:
        logger.warning("Low RAG confidence (%.2f) for theme '%s'", doc.rag_confidence, request.theme)
    return {"lyrics": doc, "artifacts": artifacts}
